
export const fylker = [
    {
      value: "agder",
      label: "Agder",
    },
    {
      value: "innlandet",
      label: "Innlandet",
    },
    {
      value: "møre og romsdal",
      label: "Møre og Romsdal",
    },
    {
      value: "nordland",
      label: "Nordland",
    },
    {
      value: "oslo",
      label: "Oslo",
    },
    {
      value: "rogaland",
      label: "Rogaland",
    },
    {
      value: "troms og finnmark",
      label: "Troms og Finnmark",
    },
    {
      value: "trøndelag",
      label: "Trøndelag",
    },
    {
      value: "vestfold og telemark",
      label: "Vestfold og Telemark",
    },
    {
      value: "vestland",
      label: "Vestland",
    },
    {
      value: "viken",
      label: "Viken",
    },
  ]
  export const kommuner = [
    { label: "Halden", value: "halden" },
    { label: "Moss", value: "Moss" },
    { label: "Sarpsborg", value: "Sarpsborg" },
    { label: "Fredrikstad", value: "Fredrikstad" },
    { label: "Drammen", value: "Drammen" },
    { label: "Kongsberg", value: "Kongsberg" },
    { label: "Ringerike", value: "Ringerike" },
    { label: "Hvaler", value: "Hvaler" },
    { label: "Aremark", value: "Aremark" },
    { label: "Marker", value: "Marker" },
    { label: "Indre Østfold", value: "Indre Østfold" },
    { label: "Skiptvet", value: "Skiptvet" },
    { label: "Rakkestad", value: "Rakkestad" },
    { label: "Råde", value: "Råde" },
    { label: "Våler", value: "Våler" },
    { label: "Vestby", value: "Vestby" },
    { label: "Nordre Follo", value: "Nordre Follo" },
    { label: "Ås", value: "Ås" },
    { label: "Frogn", value: "Frogn" },
    { label: "Nesodden", value: "Nesodden" },
    { label: "Bærum", value: "Bærum" },
    { label: "Asker", value: "Asker" },
    { label: "Aurskog-Høland", value: "Aurskog-Høland" },
    { label: "Rælingen", value: "Rælingen" },
    { label: "Enebakk", value: "Enebakk" },
    { label: "Lørenskog", value: "Lørenskog" },
    { label: "Lillestrøm", value: "Lillestrøm" },
    { label: "Nittedal", value: "Nittedal" },
    { label: "Gjerdrum", value: "Gjerdrum" },
    { label: "Ullensaker", value: "Ullensaker" },
    { label: "Nes", value: "Nes" },
    { label: "Eidsvoll", value: "Eidsvoll" },
    { label: "Nannestad", value: "Nannestad" },
    { label: "Hurdal", value: "Hurdal" },
    { label: "Hole", value: "Hole" },
    { label: "Flå", value: "Flå" },
    { label: "Nesbyen", value: "Nesbyen" },
    { label: "Gol", value: "Gol" },
    { label: "Hemsedal", value: "Hemsedal" },
    { label: "Ål", value: "Ål" },
    { label: "Hol", value: "Hol" },
    { label: "Sigdal", value: "Sigdal" },
    { label: "Krødsherad", value: "Krødsherad" },
    { label: "Modum", value: "Modum" },
    { label: "Øvre Eiker", value: "Øvre Eiker" },
    { label: "Lier", value: "Lier" },
    { label: "Flesberg", value: "Flesberg" },
    { label: "Rollag", value: "Rollag" },
    { label: "Nore og Uvdal", value: "Nore og Uvdal" },
    { label: "Jevnaker", value: "Jevnaker" },
    { label: "Lunner", value: "Lunner" },
    { label: "Oslo", value: "Oslo" },
    { label: "Kongsvinger", value: "Kongsvinger" },
    { label: "Hamar", value: "Hamar" },
    { label: "Lillehammer", value: "Lillehammer" },
    { label: "Gjøvik", value: "Gjøvik" },
    { label: "Ringsaker", value: "Ringsaker" },
    { label: "Løten", value: "Løten" },
    { label: "Stange", value: "Stange" },
    { label: "Nord-Odal", value: "Nord-Odal" },
    { label: "Sør-Odal", value: "Sør-Odal" },
    { label: "Eidskog", value: "Eidskog" },
    { label: "Grue", value: "Grue" },
    { label: "Åsnes", value: "Åsnes" },
    { label: "Elverum", value: "Elverum" },
    { label: "Trysil", value: "Trysil" },
    { label: "Åmot", value: "Åmot" },
    { label: "Stor-Elvdal", value: "Stor-Elvdal" },
    { label: "Rendalen", value: "Rendalen" },
    { label: "Engerdal", value: "Engerdal" },
    { label: "Tolga", value: "Tolga" },
    { label: "Tynset", value: "Tynset" },
    { label: "Alvdal", value: "Alvdal" },
    { label: "Folldal", value: "Folldal" },
    { label: "Os", value: "Os" },
    { label: "Dovre", value: "Dovre" },
    { label: "Lesja", value: "Lesja" },
    { label: "Skjåk", value: "Skjåk" },
    { label: "Lom", value: "Lom" },
    { label: "Vågå", value: "Vågå" },
    { label: "Nord-Fron", value: "Nord-Fron" },
    { label: "Sel", value: "Sel" },
    { label: "Sør-Fron", value: "Sør-Fron" },
    { label: "Ringebu", value: "Ringebu" },
    { label: "Øyer", value: "Øyer" },
    { label: "Gausdal", value: "Gausdal" },
    { label: "Østre Toten", value: "Østre Toten" },
    { label: "Vestre Toten", value: "Vestre Toten" },
    { label: "Gran", value: "Gran" },
    { label: "Søndre Land", value: "Søndre Land" },
    { label: "Nordre Land", value: "Nordre Land" },
    { label: "Sør-Aurdal", value: "Sør-Aurdal" },
    { label: "Etnedal", value: "Etnedal" },
    { label: "Nord-Aurdal", value: "Nord-Aurdal" },
    { label: "Vestre Slidre", value: "Vestre Slidre" },
    { label: "Øystre Slidre", value: "Øystre Slidre" },
    { label: "Vang", value: "Vang" },
    { label: "Horten", value: "Horten" },
    { label: "Holmestrand", value: "Holmestrand" },
    { label: "Tønsberg", value: "Tønsberg" },
    { label: "Sandefjord", value: "Sandefjord" },
    { label: "Larvik", value: "Larvik" },
    { label: "Porsgrunn", value: "Porsgrunn" },
    { label: "Skien", value: "Skien" },
    { label: "Notodden", value: "Notodden" },
    { label: "Færder", value: "Færder" },
    { label: "Siljan", value: "Siljan" },
    { label: "Bamble", value: "Bamble" },
    { label: "Kragerø", value: "Kragerø" },
    { label: "Drangedal", value: "Drangedal" },
    { label: "Nome", value: "Nome" },
    { label: "Midt-Telemark", value: "Midt-Telemark" },
    { label: "Tinn", value: "Tinn" },
    { label: "Hjartdal", value: "Hjartdal" },
    { label: "Seljord", value: "Seljord" },
    { label: "Kviteseid", value: "Kviteseid" },
    { label: "Nissedal", value: "Nissedal" },
    { label: "Fyresdal", value: "Fyresdal" },
    { label: "Tokke", value: "Tokke" },
    { label: "Vinje", value: "Vinje" },
    { label: "Risør", value: "Risør" },
    { label: "Grimstad", value: "Grimstad" },
    { label: "Arendal", value: "Arendal" },
    { label: "Kristiansand", value: "Kristiansand" },
    { label: "Lindesnes", value: "Lindesnes" },
    { label: "Farsund", value: "Farsund" },
    { label: "Flekkefjord", value: "Flekkefjord" },
    { label: "Gjerstad", value: "Gjerstad" },
    { label: "Vegårshei", value: "Vegårshei" },
    { label: "Tvedestrand", value: "Tvedestrand" },
    { label: "Froland", value: "Froland" },
    { label: "Lillesand", value: "Lillesand" },
    { label: "Birkenes", value: "Birkenes" },
    { label: "Åmli", value: "Åmli" },
    { label: "Iveland", value: "Iveland" },
    { label: "Evje og Hornnes", value: "Evje og Hornnes" },
    { label: "Bygland", value: "Bygland" },
    { label: "Valle", value: "Valle" },
    { label: "Bykle", value: "Bykle" },
    { label: "Vennesla", value: "Vennesla" },
    { label: "Åseral", value: "Åseral" },
    { label: "Lyngdal", value: "Lyngdal" },
    { label: "Hægebostad", value: "Hægebostad" },
    { label: "Kvinesdal", value: "Kvinesdal" },
    { label: "Sirdal", value: "Sirdal" },
    { label: "Eigersund", value: "Eigersund" },
    { label: "Stavanger", value: "Stavanger" },
    { label: "Haugesund", value: "Haugesund" },
    { label: "Sandnes", value: "Sandnes" },
    { label: "Sokndal", value: "Sokndal" },
    { label: "Lund", value: "Lund" },
    { label: "Bjerkreim", value: "Bjerkreim" },
    { label: "Hå", value: "Hå" },
    { label: "Klepp", value: "Klepp" },
    { label: "Time", value: "Time" },
    { label: "Gjesdal", value: "Gjesdal" },
    { label: "Sola", value: "Sola" },
    { label: "Randaberg", value: "Randaberg" },
    { label: "Strand", value: "Strand" },
    { label: "Hjelmeland", value: "Hjelmeland" },
    { label: "Suldal", value: "Suldal" },
    { label: "Sauda", value: "Sauda" },
    { label: "Kvitsøy", value: "Kvitsøy" },
    { label: "Bokn", value: "Bokn" },
    { label: "Tysvær", value: "Tysvær" },
    { label: "Karmøy", value: "Karmøy" },
    { label: "Utsira", value: "Utsira" },
    { label: "Vindafjord", value: "Vindafjord" },
    { label: "Bergen", value: "Bergen" },
    { label: "Kinn", value: "Kinn" },
    { label: "Etne", value: "Etne" },
    { label: "Sveio", value: "Sveio" },
    { label: "Bømlo", value: "Bømlo" },
    { label: "Stord", value: "Stord" },
    { label: "Fitjar", value: "Fitjar" },
    { label: "Tysnes", value: "Tysnes" },
    { label: "Kvinnherad", value: "Kvinnherad" },
    { label: "Ullensvang", value: "Ullensvang" },
    { label: "Eidfjord", value: "Eidfjord" },
    { label: "Ulvik", value: "Ulvik" },
    { label: "Voss", value: "Voss" },
    { label: "Kvam", value: "Kvam" },
    { label: "Samnanger", value: "Samnanger" },
    { label: "Bjørnafjorden", value: "Bjørnafjorden" },
    { label: "Austevoll", value: "Austevoll" },
    { label: "Øygarden", value: "Øygarden" },
    { label: "Askøy", value: "Askøy" },
    { label: "Vaksdal", value: "Vaksdal" },
    { label: "Modalen", value: "Modalen" },
    { label: "Osterøy", value: "Osterøy" },
    { label: "Alver", value: "Alver" },
    { label: "Austrheim", value: "Austrheim" },
    { label: "Fedje", value: "Fedje" },
    { label: "Masfjorden", value: "Masfjorden" },
    { label: "Gulen", value: "Gulen" },
    { label: "Solund", value: "Solund" },
    { label: "Hyllestad", value: "Hyllestad" },
    { label: "Høyanger", value: "Høyanger" },
    { label: "Vik", value: "Vik" },
    { label: "Sogndal", value: "Sogndal" },
    { label: "Aurland", value: "Aurland" },
    { label: "Lærdal", value: "Lærdal" },
    { label: "Årdal", value: "Årdal" },
    { label: "Luster", value: "Luster" },
    { label: "Askvoll", value: "Askvoll" },
    { label: "Fjaler", value: "Fjaler" },
    { label: "Sunnfjord", value: "Sunnfjord" },
    { label: "Bremanger", value: "Bremanger" },
    { label: "Stad", value: "Stad" },
    { label: "Gloppen", value: "Gloppen" },
    { label: "Stryn", value: "Stryn" },
    { label: "Kristiansund", value: "Kristiansund" },
    { label: "Molde", value: "Molde" },
    { label: "Ålesund", value: "Ålesund" },
    { label: "Vanylven", value: "Vanylven" },
    { label: "Sande", value: "Sande" },
    { label: "Ulstein", value: "Ulstein" },
    { label: "Hareid", value: "Hareid" },
    { label: "Ørsta", value: "Ørsta" },
    { label: "Stranda", value: "Stranda" },
    { label: "Sykkylven", value: "Sykkylven" },
    { label: "Sula", value: "Sula" },
    { label: "Giske", value: "Giske" },
    { label: "Vestnes", value: "Vestnes" },
    { label: "Rauma", value: "Rauma" },
    { label: "Aukra", value: "Aukra" },
    { label: "Averøy", value: "Averøy" },
    { label: "Gjemnes", value: "Gjemnes" },
    { label: "Tingvoll", value: "Tingvoll" },
    { label: "Sunndal", value: "Sunndal" },
    { label: "Surnadal", value: "Surnadal" },
    { label: "Smøla", value: "Smøla" },
    { label: "Aure", value: "Aure" },
    { label: "Volda", value: "Volda" },
    { label: "Fjord", value: "Fjord" },
    { label: "Hustadvika", value: "Hustadvika" },
    { label: "Trondheim", value: "Trondheim" },
    { label: "Steinkjer", value: "Steinkjer" },
    { label: "Namsos", value: "Namsos" },
    { label: "Frøya", value: "Frøya" },
    { label: "Osen", value: "Osen" },
    { label: "Oppdal", value: "Oppdal" },
    { label: "Rennebu", value: "Rennebu" },
    { label: "Røros", value: "Røros" },
    { label: "Holtålen", value: "Holtålen" },
    { label: "Midtre Gauldal", value: "Midtre Gauldal" },
    { label: "Melhus", value: "Melhus" },
    { label: "Skaun", value: "Skaun" },
    { label: "Malvik", value: "Malvik" },
    { label: "Selbu", value: "Selbu" },
    { label: "Tydal", value: "Tydal" },
    { label: "Meråker", value: "Meråker" },
    { label: "Stjørdal", value: "Stjørdal" },
    { label: "Frosta", value: "Frosta" },
    { label: "Levanger", value: "Levanger" },
    { label: "Verdal", value: "Verdal" },
    { label: "Snåsa", value: "Snåsa" },
    { label: "Lierne", value: "Lierne" },
    { label: "Røyrvik", value: "Røyrvik" },
    { label: "Namsskogan", value: "Namsskogan" },
    { label: "Grong", value: "Grong" },
    { label: "Høylandet", value: "Høylandet" },
    { label: "Overhalla", value: "Overhalla" },
    { label: "Flatanger", value: "Flatanger" },
    { label: "Leka", value: "Leka" },
    { label: "Inderøy", value: "Inderøy" },
    { label: "Indre Fosen", value: "Indre Fosen" },
    { label: "Heim", value: "Heim" },
    { label: "Hitra", value: "Hitra" },
    { label: "Ørland", value: "Ørland" },
    { label: "Åfjord", value: "Åfjord" },
    { label: "Orkland", value: "Orkland" },
    { label: "Nærøysund", value: "Nærøysund" },
    { label: "Rindal", value: "Rindal" },
    { label: "Bodø", value: "Bodø" },
    { label: "Narvik", value: "Narvik" },
    { label: "Bindal", value: "Bindal" },
    { label: "Sømna", value: "Sømna" },
    { label: "Brønnøy", value: "Brønnøy" },
    { label: "Vega", value: "Vega" },
    { label: "Vevelstad", value: "Vevelstad" },
    { label: "Herøy", value: "Herøy" },
    { label: "Alstahaug", value: "Alstahaug" },
    { label: "Leirfjord", value: "Leirfjord" },
    { label: "Vefsn", value: "Vefsn" },
    { label: "Grane", value: "Grane" },
    { label: "Hattfjelldal", value: "Hattfjelldal" },
    { label: "Dønna", value: "Dønna" },
    { label: "Nesna", value: "Nesna" },
    { label: "Hemnes", value: "Hemnes" },
    { label: "Rana", value: "Rana" },
    { label: "Lurøy", value: "Lurøy" },
    { label: "Træna", value: "Træna" },
    { label: "Rødøy", value: "Rødøy" },
    { label: "Meløy", value: "Meløy" },
    { label: "Gildeskål", value: "Gildeskål" },
    { label: "Beiarn", value: "Beiarn" },
    { label: "Saltdal", value: "Saltdal" },
    { label: "Fauske", value: "Fauske" },
    { label: "Sørfold", value: "Sørfold" },
    { label: "Steigen", value: "Steigen" },
    { label: "Lødingen", value: "Lødingen" },
    { label: "Evenes", value: "Evenes" },
    { label: "Røst", value: "Røst" },
    { label: "Værøy", value: "Værøy" },
    { label: "Flakstad", value: "Flakstad" },
    { label: "Vestvågøy", value: "Vestvågøy" },
    { label: "Vågan", value: "Vågan" },
    { label: "Hadsel", value: "Hadsel" },
    { label: "Bø", value: "Bø" },
    { label: "Øksnes", value: "Øksnes" },
    { label: "Sortland", value: "Sortland" },
    { label: "Andøy", value: "Andøy" },
    { label: "Moskenes", value: "Moskenes" },
    { label: "Hamarøy", value: "Hamarøy" },
    { label: "Tromsø", value: "Tromsø" },
    { label: "Harstad", value: "Harstad" },
    { label: "Alta", value: "Alta" },
    { label: "Vardø", value: "Vardø" },
    { label: "Vadsø", value: "Vadsø" },
    { label: "Hammerfest", value: "Hammerfest" },
    { label: "Kvæfjord", value: "Kvæfjord" },
    { label: "Tjeldsund", value: "Tjeldsund" },
    { label: "Ibestad", value: "Ibestad" },
    { label: "Gratangen", value: "Gratangen" },
    { label: "Lavangen", value: "Lavangen" },
    { label: "Bardu", value: "Bardu" },
    { label: "Salangen", value: "Salangen" },
    { label: "Målselv", value: "Målselv" },
    { label: "Sørreisa", value: "Sørreisa" },
    { label: "Dyrøy", value: "Dyrøy" },
    { label: "Senja", value: "Senja" },
    { label: "Balsfjord", value: "Balsfjord" },
    { label: "Karlsøy", value: "Karlsøy" },
    { label: "Lyngen", value: "Lyngen" },
    { label: "Storfjord", value: "Storfjord" },
    { label: "Kåfjord", value: "Kåfjord" },
    { label: "Skjervøy", value: "Skjervøy" },
    { label: "Nordreisa", value: "Nordreisa" },
    { label: "Kvænangen", value: "Kvænangen" },
    { label: "Kautokeino", value: "Kautokeino" },
    { label: "Loppa", value: "Loppa" },
    { label: "Hasvik", value: "Hasvik" },
    { label: "Måsøy", value: "Måsøy" },
    { label: "Nordkapp", value: "Nordkapp" },
    { label: "Porsanger", value: "Porsanger" },
    { label: "Karasjok", value: "Karasjok" },
    { label: "Lebesby", value: "Lebesby" },
    { label: "Gamvik", value: "Gamvik" },
    { label: "Berlevåg", value: "Berlevåg" },
    { label: "Tana", value: "Tana" },
    { label: "Nesseby", value: "Nesseby" },
    { label: "Båtsfjord", value: "Båtsfjord" },
    { label: "Sør-Varanger", value: "Sør-Varanger" },
  ]
  
  
  export const byer = [
    { label: "Åkrehamn", value: "Åkrehamn" },
    { label: "Ålesund", value: "Ålesund" },
    { label: "Alta", value: "Alta" },
    { label: "Åndalsnes", value: "Åndalsnes" },
    { label: "Arendal", value: "Arendal" },
    { label: "Ås", value: "Ås" },
    { label: "Åsgårdstrand", value: "Åsgårdstrand" },
    { label: "Askim", value: "Askim" },
    { label: "Askøy", value: "Askøy" },
    { label: "Bergen", value: "Bergen" },
    { label: "Bodø", value: "Bodø" },
    { label: "Brevik", value: "Brevik" },
    { label: "Brønnøysund", value: "Brønnøysund" },
    { label: "Brumunddal", value: "Brumunddal" },
    { label: "Bryne", value: "Bryne" },
    { label: "Drammen", value: "Drammen" },
    { label: "Drøbak", value: "Drøbak" },
    { label: "Egersund", value: "Egersund" },
    { label: "Eidsvoll", value: "Eidsvoll" },
    { label: "Elverum", value: "Elverum" },
    { label: "Fagernes", value: "Fagernes" },
    { label: "Fauske", value: "Fauske" },
    { label: "Finnsnes", value: "Finnsnes" },
    { label: "Flekkefjord", value: "Flekkefjord" },
    { label: "Florø", value: "Florø" },
    { label: "Førde", value: "Førde" },
    { label: "Fosnavåg", value: "Fosnavåg" },
    { label: "Fredrikstad", value: "Fredrikstad" },
    { label: "Gjøvik", value: "Gjøvik" },
    { label: "Grimstad", value: "Grimstad" },
    { label: "Halden", value: "Halden" },
    { label: "Hamar", value: "Hamar" },
    { label: "Hammerfest", value: "Hammerfest" },
    { label: "Harstad", value: "Harstad" },
    { label: "Haugesund", value: "Haugesund" },
    { label: "Hokksund", value: "Hokksund" },
    { label: "Holmestrand", value: "Holmestrand" },
    { label: "Hønefoss", value: "Hønefoss" },
    { label: "Honningsvåg", value: "Honningsvåg" },
    { label: "Horten", value: "Horten" },
    { label: "Jessheim", value: "Jessheim" },
    { label: "Jørpeland", value: "Jørpeland" },
    { label: "Kirkenes", value: "Kirkenes" },
    { label: "Kongsberg", value: "Kongsberg" },
    { label: "Kongsvinger", value: "Kongsvinger" },
    { label: "Kopervik", value: "Kopervik" },
    { label: "Kragerø", value: "Kragerø" },
    { label: "Kristiansand", value: "Kristiansand" },
    { label: "Kristiansund", value: "Kristiansund" },
    { label: "Langesund", value: "Langesund" },
    { label: "Larvik", value: "Larvik" },
    { label: "Leknes", value: "Leknes" },
    { label: "Levanger", value: "Levanger" },
    { label: "Lillehammer", value: "Lillehammer" },
    { label: "Lillesand", value: "Lillesand" },
    { label: "Lillestrøm", value: "Lillestrøm" },
    { label: "Lyngdal", value: "Lyngdal" },
    { label: "Mandal", value: "Mandal" },
    { label: "Moelv", value: "Moelv" },
    { label: "Mo i rana", value: "Mo i Rana" },
    { label: "Molde", value: "Molde" },
    { label: "Mosjøen", value: "Mosjøen" },
    { label: "Moss", value: "Moss" },
    { label: "Nærøy", value: "Nærøy" },
    { label: "Namsos", value: "Namsos" },
    { label: "Narvik", value: "Narvik" },
    { label: "Nesoddtangen", value: "Nesoddtangen" },
    { label: "Notodden", value: "Notodden" },
    { label: "Odda", value: "Odda" },
    { label: "Orkanger", value: "Orkanger" },
    { label: "Oslo", value: "Oslo" },
    { label: "Otta", value: "Otta" },
    { label: "Porsgrunn", value: "Porsgrunn" },
    { label: "Raufoss", value: "Raufoss" },
    { label: "Risør", value: "Risør" },
    { label: "Rjukan", value: "Rjukan" },
    { label: "Sandefjord", value: "Sandefjord" },
    { label: "Sandnes", value: "Sandnes" },
    { label: "Sandnessjøen", value: "Sandnessjøen" },
    { label: "Sandvika", value: "Sandvika" },
    { label: "Sauda", value: "Sauda" },
    { label: "Ski", value: "Ski" },
    { label: "Skien", value: "Skien" },
    { label: "Sortland", value: "Sortland" },
    { label: "Stavanger", value: "Stavanger" },
    { label: "Stavern", value: "Stavern" },
    { label: "Steinkjer", value: "Steinkjer" },
    { label: "Stjørdal", value: "Stjørdal" },
    { label: "Stokmarknes", value: "Stokmarknes" },
    { label: "Stord", value: "Stord" },
    { label: "Svelvik", value: "Svelvik" },
    { label: "Svolvær", value: "Svolvær" },
    { label: "Tønsberg", value: "Tønsberg" },
    { label: "Tromsø", value: "Tromsø" },
    { label: "Trondheim", value: "Trondheim" },
    { label: "Tvedestrand", value: "Tvedestrand" },
    { label: "Ulsteinvik", value: "Ulsteinvik" },
    { label: "Vadsø", value: "Vadsø" },
    { label: "Vardø", value: "Vardø" },
    { label: "Farsund", value: "Farsund" },
    { label: "Måløy", value: "Måløy" },
    { label: "Verdal", value: "Verdal" },
    { label: "Vestby", value: "Vestby" },
    { label: "Vinstra", value: "Vinstra" },
  ]
  
  export const NACE = [
    { label: "Jordbruk, skogbruk og fiske", value: "1" },
    { label: "Skogbruk og tømmerhogst", value: "2" },
    { label: "Fiske og akvakultur", value: "3" },
    { label: "Kullgruvedrift", value: "5" },
    { label: "Utvinning av råolje og naturgass", value: "6" },
    { label: "Utvinning av metallmalm", value: "7" },
    { label: "Annen gruvedrift og utvinning", value: "8" },
    { label: "Tjenester tilknyttet gruvedrift", value: "9" },
    { label: "Produksjon av matvarer", value: "10" },
    { label: "Produksjon av drikkevarer", value: "11" },
    { label: "Produksjon av tobakksvarer", value: "12" },
    { label: "Tekstilproduksjon", value: "13" },
    { label: "Produksjon av klesvarer", value: "14" },
    { label: "Produksjon av lær og lærvarer", value: "15" },
    { label: "Trebearbeiding og produksjon av varer av tre", value: "16" },
    { label: "Papirproduksjon", value: "17" },
    { label: "Trykking og reprodusering av opptak", value: "18" },
    {
      label: "Produksjon av koks og raffinerte petroleumsprodukter",
      value: "19",
    },
    { label: "Kjemisk produksjon", value: "20" },
    {
      label: "Produksjon av farmasøytiske grunnstoffer og preparater",
      value: "21",
    },
    { label: "Produksjon av gummi- og plastvarer", value: "22" },
    {
      label: "Produksjon av andre ikke-metallholdige mineralprodukter",
      value: "23",
    },
    { label: "Metallproduksjon", value: "24" },
    {
      label: "Produksjon av metallvarer, unntatt maskiner og utstyr",
      value: "25",
    },
    {
      label: "Produksjon av datamaskiner og elektroniske og optiske produkter",
      value: "26",
    },
    { label: "Elektrisk utstyrsproduksjon", value: "27" },
    { label: "Produksjon av maskiner og utstyr n.e.c.", value: "28" },
    {
      label: "Produksjon av motorvogner, tilhengere og semitrailere",
      value: "29",
    },
    { label: "Produksjon av andre transportmidler", value: "30" },
    { label: "Produksjon av møbler", value: "31" },
    { label: "Annet produksjon", value: "32" },
    { label: "Reparasjon og installasjon av maskiner og utstyr", value: "33" },
    {
      label: "Elektrisitets-, gass-, damp- og luftkondisjoneringsforsyning",
      value: "35",
    },
    {
      label: "Vannforsyning; avløps-, avfallsbehandling og sanering",
      value: "36",
    },
    { label: "Avløpsbehandling og avfallshåndtering", value: "37" },
    {
      label: "Innsamling, behandling og deponering av avfall; gjenvinning",
      value: "38",
    },
    { label: "Sanering og annen avfallshåndtering", value: "39" },
    { label: "Bygging av bygninger", value: "41" },
    { label: "Anleggsvirksomhet", value: "42" },
    { label: "Spesialisert bygge- og anleggsvirksomhet", value: "43" },
    {
      label:
        "Engroshandel og detaljhandel med motorvogner; reparasjon av motorvogner",
      value: "45",
    },
    { label: "Engroshandel, unntatt med motorvogner", value: "46" },
    { label: "Detaljhandel, unntatt med motorvogner", value: "47" },
    { label: "Landtransport og transport i rørledninger", value: "49" },
    { label: "Sjøtransport", value: "50" },
    { label: "Lufttransport", value: "51" },
    { label: "Lager og støttetjenester til transport", value: "52" },
    { label: "Post og kurertjenester", value: "53" },
    { label: "Overnatting", value: "55" },
    { label: "Serveringstjenester", value: "56" },
    { label: "Forlagsvirksomhet", value: "58" },
    {
      label:
        "Film-, video- og tv-programproduksjon, lydopptak og musikkutgivelse",
      value: "59",
    },
    { label: "Programmering og kringkasting av fjernsyn og radio", value: "60" },
    { label: "Telekommunikasjon", value: "61" },
    { label: "Konsulenttjenester innen informasjonsteknologi", value: "62" },
    { label: "Informasjonstjenester", value: "63" },
    {
      label: "Finansiell tjenesteyting, unntatt forsikring og pensjonsfond",
      value: "64",
    },
    {
      label:
        "Forsikring, reassuranse og pensjonsfond, unntatt obligatorisk sosialforsikring",
      value: "65",
    },
    {
      label:
        "Tjenester tilknyttet finansiell tjenesteyting og forsikringsvirksomhet",
      value: "66",
    },
    { label: "Eiendomsomsetning", value: "68" },
    { label: "Juridisk og regnskapsmessig tjenesteyting", value: "69" },
    { label: "Tjenester tilknyttet bedriftsledelse", value: "70" },
    {
      label: "Arkitekt- og ingeniørvirksomhet; teknisk testing og analyse",
      value: "71",
    },
    {
      label: "Forskning og utvikling innen naturvitenskap og teknologi",
      value: "72",
    },
    { label: "Reklame og markedsundersøkelse", value: "73" },
    {
      label: "Annen profesjonell, vitenskapelig og teknisk virksomhet",
      value: "74",
    },
    { label: "Veterinærtjenester", value: "75" },
    {
      label: "Utleie og leasing av andre maskiner, annet utstyr og andre varer",
      value: "77",
    },
    { label: "Arbeidskraftformidling og tilknyttede tjenester", value: "78" },
    {
      label:
        "Reisebyrå-, reisearrangør-, turistguide- og andre reservasjonstjenester",
      value: "79",
    },
    { label: "Vakttjenester og etterforskningsvirksomhet", value: "80" },
    { label: "Tjenester tilknyttet bygninger og landskapspleie", value: "81" },
    {
      label: "Kontortjenester og andre forretningsmessige tjenester",
      value: "82",
    },
    {
      label: "Offentlig administrasjon og forsvar; obligatorisk sosialforsikring",
      value: "84",
    },
    { label: "Utdanning", value: "85" },
    { label: "Helse- og sosialtjenester", value: "86" },
    { label: "Institusjonsomsorg", value: "87" },
    { label: "Sosiale tjenester uten institusjonsomsorg", value: "88" },
    {
      label: "Kreative, kunstneriske og underholdningsmessige aktiviteter",
      value: "90",
    },
    {
      label: "Biblioteker, arkiver, museer og annen kulturell virksomhet",
      value: "91",
    },
    { label: "Pengespill og lotterivirksomhet", value: "92" },
    { label: "Sports- og fritidsaktiviteter", value: "93" },
    { label: "Interesseorganisasjoners virksomhet", value: "94" },
    { label: "Reparasjon av datamaskiner og husholdningsvarer", value: "95" },
    { label: "Annen personlig tjenesteyting", value: "96" },
    { label: "Privathusholdninger med ansatte tjenestepersoner", value: "97" },
    { label: "Uoppgitt virksomhet i utlandet", value: "98" },
    { label: "Internasjonale organisasjoner og organer", value: "99" },
  ]
  
  export const NACE_nmbr_grp = [
    { label: "Adresseringsleverandører", value: "Adresseringsleverandører" },
    {
      label: "Advokater og juridiske tjenester",
      value: "Advokater og juridiske tjenester",
    },
    { label: "Agenturer", value: "Agenturer" },
    { label: "Andre transportmidler", value: "Andre transportmidler" },
    { label: "Anleggsmaskiner og -utstyr", value: "Anleggsmaskiner og -utstyr" },
    {
      label: "Annen forretningsmessig tjenesteyting",
      value: "Annen forretningsmessig tjenesteyting",
    },
    { label: "Annen industri", value: "Annen industri" },
    { label: "Annen industriproduksjon", value: "Annen industriproduksjon" },
    { label: "Annen tjenesteyting", value: "Annen tjenesteyting" },
    { label: "Arbeidskrafttjenester", value: "Arbeidskrafttjenester" },
    { label: "Arbeidstakerorganisasjoner", value: "Arbeidstakerorganisasjoner" },
    { label: "Arkitekttjenester", value: "Arkitekttjenester" },
    { label: "Asylmottak", value: "Asylmottak" },
    {
      label: "Avfallsbehandling og -gjenvinning",
      value: "Avfallsbehandling og -gjenvinning",
    },
    {
      label: "Aviser, fagblader og tidsskrifter",
      value: "Aviser, fagblader og tidsskrifter",
    },
    {
      label: "Bakeri- og konditoriråvarer",
      value: "Bakeri- og konditoriråvarer",
    },
    { label: "Banker", value: "Banker" },
    { label: "Barer og puber", value: "Barer og puber" },
    {
      label: "Barnehager, -parker og dagmammaer",
      value: "Barnehager, -parker og dagmammaer",
    },
    { label: "Båtbyggerier", value: "Båtbyggerier" },
    { label: "Batterier", value: "Batterier" },
    {
      label: "Begravelsesbyråer, drift av kirkegårder og krematorier",
      value: "Begravelsesbyråer, drift av kirkegårder og krematorier",
    },
    { label: "Bekledningsindustri", value: "Bekledningsindustri" },
    {
      label: "Beplantning av hager og parkanlegg",
      value: "Beplantning av hager og parkanlegg",
    },
    { label: "Biblioteker og arkiver", value: "Biblioteker og arkiver" },
    { label: "Biler og kjøretøy", value: "Biler og kjøretøy" },
    { label: "Bioteknologi", value: "Bioteknologi" },
    { label: "Blikkenslagere og utstyr", value: "Blikkenslagere og utstyr" },
    { label: "Bokbinderier", value: "Bokbinderier" },
    {
      label: "Bøker, papir, aviser og blader",
      value: "Bøker, papir, aviser og blader",
    },
    { label: "Boligbyggelag", value: "Boligbyggelag" },
    { label: "Bomstasjoner", value: "Bomstasjoner" },
    { label: "Borettslag", value: "Borettslag" },
    {
      label: "Botaniske og zoologiske hager og naturreservater",
      value: "Botaniske og zoologiske hager og naturreservater",
    },
    { label: "Brannvern", value: "Brannvern" },
    {
      label: "Bryting av metallholdig malm",
      value: "Bryting av metallholdig malm",
    },
    {
      label: "Bryting av steinkull og brunkull",
      value: "Bryting av steinkull og brunkull",
    },
    { label: "Bryting og bergverksdrift", value: "Bryting og bergverksdrift" },
    {
      label: "Bryting og bergverksdrift - tjenester",
      value: "Bryting og bergverksdrift - tjenester",
    },
    { label: "Budtjenester", value: "Budtjenester" },
    { label: "Busselskaper", value: "Busselskaper" },
    { label: "Butikkhandel", value: "Butikkhandel" },
    {
      label: "Bygg- og anleggsleverandører",
      value: "Bygg- og anleggsleverandører",
    },
    { label: "Bygg- og tømrermestere", value: "Bygg- og tømrermestere" },
    {
      label: "Bygge- og anleggsvirksomhet",
      value: "Bygge- og anleggsvirksomhet",
    },
    { label: "Catering", value: "Catering" },
    {
      label: "Damp- og varmtvannsforsyning",
      value: "Damp- og varmtvannsforsyning",
    },
    { label: "Designere", value: "Designere" },
    { label: "Detaljhandel", value: "Detaljhandel" },
    { label: "Drikkevarer", value: "Drikkevarer" },
    { label: "Drosjer", value: "Drosjer" },
    {
      label: "Eiendomsforvaltning og -utvikling",
      value: "Eiendomsforvaltning og -utvikling",
    },
    { label: "Eiendomshandel og -utleie", value: "Eiendomshandel og -utleie" },
    { label: "Eiendomsmegling", value: "Eiendomsmegling" },
    {
      label: "Elektrisk installasjonsarbeid",
      value: "Elektrisk installasjonsarbeid",
    },
    {
      label: "Elektroteknikk - produkter og utstyr",
      value: "Elektroteknikk - produkter og utstyr",
    },
    { label: "Engroshandel - annet", value: "Engroshandel - annet" },
    { label: "Entreprenører", value: "Entreprenører" },
    { label: "Etterforsking", value: "Etterforsking" },
    {
      label: "Faglig, vitenskapelig og teknisk virksomhet",
      value: "Faglig, vitenskapelig og teknisk virksomhet",
    },
    { label: "Fagskoler", value: "Fagskoler" },
    {
      label: "Farmasøytiske råvarer og preparater",
      value: "Farmasøytiske råvarer og preparater",
    },
    { label: "Fiberoptikk", value: "Fiberoptikk" },
    { label: "Film- og videotjenester", value: "Film- og videotjenester" },
    { label: "Filmframvisning", value: "Filmframvisning" },
    { label: "Finans", value: "Finans" },
    { label: "Finansiering", value: "Finansiering" },
    { label: "Fiske", value: "Fiske" },
    { label: "Fiskeforedling og -utstyr", value: "Fiskeforedling og -utstyr" },
    { label: "Flymegling", value: "Flymegling" },
    { label: "Flyttetjenester", value: "Flyttetjenester" },
    { label: "Forlag", value: "Forlag" },
    { label: "Fornøyelses- og temaparker", value: "Fornøyelses- og temaparker" },
    { label: "Forsikring", value: "Forsikring" },
    { label: "Forskning og utvikling", value: "Forskning og utvikling" },
    { label: "Forsyningsbaser", value: "Forsyningsbaser" },
    { label: "Fotografering", value: "Fotografering" },
    { label: "Frisører o.l.", value: "Frisører o.l." },
    { label: "Frukt, bær og grønnsaker", value: "Frukt, bær og grønnsaker" },
    { label: "Gassproduksjon", value: "Gassproduksjon" },
    { label: "Gatekjøkken", value: "Gatekjøkken" },
    {
      label: "Gipsprodukter, gips og kalk",
      value: "Gipsprodukter, gips og kalk",
    },
    { label: "Gjødsel", value: "Gjødsel" },
    { label: "Glass og glassarbeid", value: "Glass og glassarbeid" },
    { label: "Glassindustri", value: "Glassindustri" },
    { label: "Gods- og varetransport", value: "Gods- og varetransport" },
    { label: "Grafiske tjenester", value: "Grafiske tjenester" },
    { label: "Guider", value: "Guider" },
    { label: "Gull- og sølvvarer", value: "Gull- og sølvvarer" },
    { label: "Gummi og plastprodukter", value: "Gummi og plastprodukter" },
    { label: "Hav- og kystfiske", value: "Hav- og kystfiske" },
    { label: "Helsetjenester", value: "Helsetjenester" },
    {
      label: "Historiske steder og bygninger",
      value: "Historiske steder og bygninger",
    },
    { label: "Holdingselskaper", value: "Holdingselskaper" },
    {
      label: "Hoteller og andre overnattingssteder",
      value: "Hoteller og andre overnattingssteder",
    },
    { label: "Hovedkontortjenester", value: "Hovedkontortjenester" },
    { label: "Høyskoler og universiteter", value: "Høyskoler og universiteter" },
    {
      label: "Husholdningsmaskiner og -apparater",
      value: "Husholdningsmaskiner og -apparater",
    },
    { label: "Idrettsanlegg og -utstyr", value: "Idrettsanlegg og -utstyr" },
    { label: "Idrettslag og -klubber", value: "Idrettslag og -klubber" },
    { label: "Industri", value: "Industri" },
    {
      label: "Informasjon og informasjonsrådgivning",
      value: "Informasjon og informasjonsrådgivning",
    },
    { label: "Inkasso", value: "Inkasso" },
    {
      label: "Internasjonale organisasjoner og organer",
      value: "Internasjonale organisasjoner og organer",
    },
    {
      label: "Internettdesign og programmering",
      value: "Internettdesign og programmering",
    },
    { label: "IT - annet", value: "IT - annet" },
    { label: "IT-drift og support", value: "IT-drift og support" },
    {
      label: "Jakt, viltstell og tjenester tilknyttet jakt og viltstell",
      value: "Jakt, viltstell og tjenester tilknyttet jakt og viltstell",
    },
    { label: "Jern, stål og metaller", value: "Jern, stål og metaller" },
    { label: "Jernbane og sporvei", value: "Jernbane og sporvei" },
    { label: "Jordbruk", value: "Jordbruk" },
    { label: "Jordbruk - andre tjenester", value: "Jordbruk - andre tjenester" },
    { label: "Jordbruk - melkeproduksjon", value: "Jordbruk - melkeproduksjon" },
    {
      label: "Jordbruk - oppdrett og husdyrhold",
      value: "Jordbruk - oppdrett og husdyrhold",
    },
    { label: "Kantinetjenester", value: "Kantinetjenester" },
    {
      label: "Karosserifabrikker og -verksteder",
      value: "Karosserifabrikker og -verksteder",
    },
    { label: "Keramiske produkter", value: "Keramiske produkter" },
    {
      label: "Kjemikalier og kjemiske varer",
      value: "Kjemikalier og kjemiske varer",
    },
    { label: "Kjemisk industri", value: "Kjemisk industri" },
    {
      label: "Kjøle- og ventilasjonsanlegg",
      value: "Kjøle- og ventilasjonsanlegg",
    },
    { label: "Kjøtt og vilt", value: "Kjøtt og vilt" },
    {
      label: "Klær, sko, utstyrsvarer, reiseeffekter og tekstiler",
      value: "Klær, sko, utstyrsvarer, reiseeffekter og tekstiler",
    },
    { label: "Klokker og ur", value: "Klokker og ur" },
    { label: "Kontor- og teletjenester", value: "Kontor- og teletjenester" },
    { label: "Kopiering", value: "Kopiering" },
    {
      label: "Korn, råtobakk, såvarer og fôrvarer",
      value: "Korn, råtobakk, såvarer og fôrvarer",
    },
    { label: "Koster og børster", value: "Koster og børster" },
    { label: "Kraftforsyning", value: "Kraftforsyning" },
    { label: "Kredittjenester", value: "Kredittjenester" },
    {
      label: "Kull- og raffinerte petroleumsprodukter",
      value: "Kull- og raffinerte petroleumsprodukter",
    },
    { label: "Kunstnerisk virksomhet", value: "Kunstnerisk virksomhet" },
    { label: "Lager", value: "Lager" },
    {
      label: "Landskapsarkitekter og -konsulenter",
      value: "Landskapsarkitekter og -konsulenter",
    },
    { label: "Låser og beslag", value: "Låser og beslag" },
    { label: "Lasting og lossing", value: "Lasting og lossing" },
    { label: "Leger", value: "Leger" },
    {
      label: "Lønnet arbeid i private husholdninger",
      value: "Lønnet arbeid i private husholdninger",
    },
    {
      label: "Lotteri- og spillvirksomhet",
      value: "Lotteri- og spillvirksomhet",
    },
    {
      label: "Luftfartøyer og romfartøyer",
      value: "Luftfartøyer og romfartøyer",
    },
    { label: "Lysanlegg og -utstyr", value: "Lysanlegg og -utstyr" },
    { label: "Malere", value: "Malere" },
    { label: "Maling og lakk", value: "Maling og lakk" },
    { label: "Markedsundersøkelser", value: "Markedsundersøkelser" },
    { label: "Maskiner og utstyr", value: "Maskiner og utstyr" },
    {
      label: "Maskiner og utstyr - reparasjon",
      value: "Maskiner og utstyr - reparasjon",
    },
    {
      label: "Medie- og kommunikasjonsrådgivning",
      value: "Medie- og kommunikasjonsrådgivning",
    },
    { label: "Mediebyråer", value: "Mediebyråer" },
    { label: "Medlemsorganisasjoner", value: "Medlemsorganisasjoner" },
    {
      label: "Meierivarer, egg, matolje og -fett",
      value: "Meierivarer, egg, matolje og -fett",
    },
    {
      label: "Miljørydding og miljørensing",
      value: "Miljørydding og miljørensing",
    },
    { label: "Mineralproduktindustri", value: "Mineralproduktindustri" },
    {
      label: "Møbler, innredning, kjøkken- og belysningsutstyr",
      value: "Møbler, innredning, kjøkken- og belysningsutstyr",
    },
    { label: "Modellbyråer", value: "Modellbyråer" },
    { label: "Motorer og motoroverhaling", value: "Motorer og motoroverhaling" },
    {
      label: "Motorsykler, mopeder og scootere",
      value: "Motorsykler, mopeder og scootere",
    },
    { label: "Murstein og teglstein", value: "Murstein og teglstein" },
    { label: "Museer og samlinger", value: "Museer og samlinger" },
    { label: "Musikk", value: "Musikk" },
    { label: "Musikkinstrumenter", value: "Musikkinstrumenter" },
    { label: "Næringsmiddelindustri", value: "Næringsmiddelindustri" },
    { label: "Nyhets- og telegrambyråer", value: "Nyhets- og telegrambyråer" },
    { label: "Offentlig administrasjon", value: "Offentlig administrasjon" },
    { label: "Olje og gass", value: "Olje og gass" },
    { label: "Olje og oljevarer", value: "Olje og oljevarer" },
    { label: "Oversettere og tolker", value: "Oversettere og tolker" },
    { label: "Papir og papirprodukter", value: "Papir og papirprodukter" },
    { label: "Parkeringsanlegg", value: "Parkeringsanlegg" },
    {
      label: "Partipolitiske organisasjoner",
      value: "Partipolitiske organisasjoner",
    },
    { label: "Pensjonskasser", value: "Pensjonskasser" },
    { label: "Personlig tjenesteyting", value: "Personlig tjenesteyting" },
    { label: "Plan- og reguleringsarbeid", value: "Plan- og reguleringsarbeid" },
    { label: "Pleie- og omsorgstjenester", value: "Pleie- og omsorgstjenester" },
    { label: "Politi- og påtalemyndighet", value: "Politi- og påtalemyndighet" },
    { label: "Postordre-/internetthandel", value: "Postordre-/internetthandel" },
    { label: "Posttjenester", value: "Posttjenester" },
    {
      label: "Rådgivende ingeniører - Bygge- og anleggsteknikk",
      value: "Rådgivende ingeniører - Bygge- og anleggsteknikk",
    },
    {
      label: "Rådgivende ingeniører - Geoteknikk og ingeniørgeologi",
      value: "Rådgivende ingeniører - Geoteknikk og ingeniørgeologi",
    },
    {
      label: "Rådgivende ingeniører - Øvrige",
      value: "Rådgivende ingeniører - Øvrige",
    },
    { label: "Redningstjenester", value: "Redningstjenester" },
    { label: "Regnskapstjenester", value: "Regnskapstjenester" },
    {
      label: "Rehabilitering og opptreningssentre",
      value: "Rehabilitering og opptreningssentre",
    },
    { label: "Reiselivstjenester", value: "Reiselivstjenester" },
    { label: "Reklamebyråer", value: "Reklamebyråer" },
    { label: "Religiøse organisasjoner", value: "Religiøse organisasjoner" },
    { label: "Rengjøring", value: "Rengjøring" },
    { label: "Reparatører", value: "Reparatører" },
    { label: "Restauranter og kafeer", value: "Restauranter og kafeer" },
    { label: "Retts- og fengselsvesen", value: "Retts- og fengselsvesen" },
    { label: "Revisjonstjenester", value: "Revisjonstjenester" },
    { label: "Rivingsarbeid", value: "Rivingsarbeid" },
    { label: "Romfart", value: "Romfart" },
    { label: "Rørtransport", value: "Rørtransport" },
    { label: "Sagbruk og høvlerier", value: "Sagbruk og høvlerier" },
    { label: "Sement, mørtel og betong", value: "Sement, mørtel og betong" },
    { label: "Shipping og sjøtransport", value: "Shipping og sjøtransport" },
    { label: "Skadedyrbekjempelse", value: "Skadedyrbekjempelse" },
    { label: "Skatterådgivning", value: "Skatterådgivning" },
    { label: "Skinn, lær og pels", value: "Skinn, lær og pels" },
    { label: "Skipsbyggerier og -verft", value: "Skipsbyggerier og -verft" },
    { label: "Skipsmeglere", value: "Skipsmeglere" },
    { label: "Skipsutstyr", value: "Skipsutstyr" },
    { label: "Skogbruk", value: "Skogbruk" },
    { label: "Skolefritidsordninger", value: "Skolefritidsordninger" },
    { label: "Skoler og undervisning", value: "Skoler og undervisning" },
    { label: "Snekkere", value: "Snekkere" },
    { label: "Spedisjon og fortolling", value: "Spedisjon og fortolling" },
    { label: "Spill og leker", value: "Spill og leker" },
    { label: "Sports- og fritidsutstyr", value: "Sports- og fritidsutstyr" },
    { label: "Strømselskap", value: "Strømselskap" },
    { label: "Sykehjem", value: "Sykehjem" },
    { label: "Sykehus", value: "Sykehus" },
    { label: "Takseringstjenester", value: "Takseringstjenester" },
    { label: "Tanker", value: "Tanker" },
    { label: "Tannhelse", value: "Tannhelse" },
    {
      label: "Tannlege- og tannteknikerrekvisita",
      value: "Tannlege- og tannteknikerrekvisita",
    },
    { label: "Teknisk prøving og analyse", value: "Teknisk prøving og analyse" },
    { label: "Tekniske konsulenter", value: "Tekniske konsulenter" },
    { label: "Tekstiler og tilbehør", value: "Tekstiler og tilbehør" },
    { label: "Telefonmarkedsføring", value: "Telefonmarkedsføring" },
    { label: "Telekommunikasjon", value: "Telekommunikasjon" },
    { label: "Tobakk", value: "Tobakk" },
    { label: "Torghandel", value: "Torghandel" },
    { label: "Trafikkskoler", value: "Trafikkskoler" },
    { label: "Transport", value: "Transport" },
    {
      label: "Transportmiddelindustri ellers",
      value: "Transportmiddelindustri ellers",
    },
    {
      label: "Trelast- og trevareindustri",
      value: "Trelast- og trevareindustri",
    },
    {
      label: "Treningssentre og andre sportsaktiviteter",
      value: "Treningssentre og andre sportsaktiviteter",
    },
    { label: "Trevarer", value: "Trevarer" },
    { label: "Trykkeritjenester", value: "Trykkeritjenester" },
    { label: "Turkjøring", value: "Turkjøring" },
    { label: "TV og Radio", value: "TV og Radio" },
    {
      label: "Underholdning- og arrangørtjenester",
      value: "Underholdning- og arrangørtjenester",
    },
    { label: "Utleie og leasing", value: "Utleie og leasing" },
    {
      label: "Utstillinger og utstillingslokaler",
      value: "Utstillinger og utstillingslokaler",
    },
    { label: "Vaktmestertjenester", value: "Vaktmestertjenester" },
    { label: "Vaktselskaper", value: "Vaktselskaper" },
    { label: "Vann og kloakk", value: "Vann og kloakk" },
    { label: "Våpen og ammunisjon", value: "Våpen og ammunisjon" },
    {
      label: "Varme- og sanitær-anlegg og -utstyr",
      value: "Varme- og sanitær-anlegg og -utstyr",
    },
    { label: "Vaskerier og renserier", value: "Vaskerier og renserier" },
    {
      label: "Verdipapir og fondsforvaltning",
      value: "Verdipapir og fondsforvaltning",
    },
    { label: "Verktøy og redskaper", value: "Verktøy og redskaper" },
    { label: "Veterinærtjenester", value: "Veterinærtjenester" },
    { label: "Yrkessammenslutninger", value: "Yrkessammenslutninger" },
  ]
  